# syntax = docker/dockerfile:1.7@sha256:a57df69d0ea827fb7266491f2813635de6f17269be881f696fbfdf2d83dda33e

# Copyright 2020-2022 Datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=$BUILDPLATFORM golang:1.27.1-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125 AS tel2-build

RUN apk add --no-cache gcc musl-dev fuse-dev libcap binutils-gold

WORKDIR /go/telepresence
COPY go.mod go.sum .
COPY cmd/ cmd/
COPY pkg/ pkg/
COPY rpc/ rpc/
COPY charts/ charts/
# This ignored input must also be present when BuildKit reads the source directly from Git.
ADD --checksum=sha256:a9e98cdc6ab09980f23b5e987a5f11d0ec1fc838187efb92f347ccf38ed8fd65 --chmod=0644 https://raw.githubusercontent.com/yannh/kubernetes-json-schema/629fd45755a7eb4992f76a3be8cf040b57db9ce6/v1.36.2-standalone/_definitions.json charts/telepresence-oss/k8s-defs.json

ARG TARGETOS
ARG TARGETARCH
ARG TELEPRESENCE_VERSION

# TEL_COVER is "-cover" when the image is built with `make tel2-image
# TELEPRESENCE_COVER=1`, and empty (today's behavior) otherwise.
ARG TEL_COVER=

RUN \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    test -n "$TELEPRESENCE_VERSION" && \
    test "$(go list -m -f '{{.Version}}' k8s.io/client-go)" = v0.36.2 && \
    GOOS=$TARGETOS GOARCH=$TARGETARCH go build $TEL_COVER -o /usr/local/bin/ -trimpath -ldflags="-s -w -X=$(go list ./pkg/version).Version=$TELEPRESENCE_VERSION" ./cmd/traffic/...

# The tel2 target is the one that gets published. It aims to be a small as possible.
FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b AS tel2

RUN apk add --no-cache ca-certificates

# the traffic binary
COPY --from=tel2-build /usr/local/bin/traffic /usr/local/bin

RUN \
  mkdir /tel_app_mounts && \
  chgrp -R 0 /tel_app_mounts && \
  chmod -R g=u /tel_app_mounts && \
  mkdir -p /home/telepresence && \
  chgrp -R 0 /home/telepresence && \
  chmod -R g=u /home/telepresence && \
  chmod 0777 /home/telepresence

ENTRYPOINT ["traffic"]
CMD []
